echo 'Останавливаю сигнатурные анализаторы'
/bin/argsh -c "services analyzer ids0 stop; services analyzer ids1 stop; services analyzer ids2 stop"

echo 'Настройка ids0'
/bin/argsh -c "services analyzer ids0 rules enable system check_listen_interface.ids; services analyzer ids0 rules enable system detect-ftp-bruteforcing.ids; services analyzer ids0 rules enable system detect-http-bruteforcing.ids; services analyzer ids0 rules enable system detect-http-xss.ids; services analyzer ids0 rules enable system detect-sqlinjection.ids; services analyzer ids0 rules enable system detect-ssh-bruteforcing.ids; services analyzer ids0 rules enable system scan.ids; services analyzer ids0 rules enable system signatures/attempted-admin.ids; services analyzer ids0 rules enable system signatures/attempted-dos.ids; services analyzer ids0 rules enable system signatures/attempted-recon.ids; services analyzer ids0 rules enable system signatures/attempted-user.ids; services analyzer ids0 rules enable system signatures/bad-unknown.ids; services analyzer ids0 rules enable system signatures/default-login-attempt.ids; services analyzer ids0 rules enable system signatures/denial-of-service.ids; services analyzer ids0 rules enable system signatures/misc-attack.ids; services analyzer ids0 rules enable system signatures/policy-violation.ids; services analyzer ids0 rules enable system signatures/protocol-command-decode.ids; services analyzer ids0 rules enable system signatures/successful-recon-largescale.ids; services analyzer ids0 rules enable system signatures/suspicious-filename-detect.ids; services analyzer ids0 rules enable system signatures/trojan-activity.ids; services analyzer ids0 rules enable system signatures/unknown.ids; services analyzer ids0 rules enable system signatures/web-application-activity.ids; services analyzer ids0 rules enable system signatures/web-application-attack.ids"

echo 'Настройка ids1'
/bin/argsh -c "services analyzer ids1 rules enable system check_listen_interface.ids; services analyzer ids1 rules enable system detect-ftp-bruteforcing.ids; services analyzer ids1 rules enable system detect-http-bruteforcing.ids; services analyzer ids1 rules enable system detect-http-xss.ids; services analyzer ids1 rules enable system detect-sqlinjection.ids; services analyzer ids1 rules enable system detect-ssh-bruteforcing.ids; services analyzer ids1 rules enable system scan.ids; services analyzer ids1 rules enable system signatures/attempted-admin.ids; services analyzer ids1 rules enable system signatures/attempted-dos.ids; services analyzer ids1 rules enable system signatures/attempted-recon.ids; services analyzer ids1 rules enable system signatures/attempted-user.ids; services analyzer ids1 rules enable system signatures/bad-unknown.ids; services analyzer ids1 rules enable system signatures/default-login-attempt.ids; services analyzer ids1 rules enable system signatures/denial-of-service.ids; services analyzer ids1 rules enable system signatures/misc-attack.ids; services analyzer ids1 rules enable system signatures/policy-violation.ids; services analyzer ids1 rules enable system signatures/protocol-command-decode.ids; services analyzer ids1 rules enable system signatures/successful-recon-largescale.ids; services analyzer ids1 rules enable system signatures/suspicious-filename-detect.ids; services analyzer ids1 rules enable system signatures/trojan-activity.ids; services analyzer ids1 rules enable system signatures/unknown.ids; services analyzer ids1 rules enable system signatures/web-application-activity.ids; services analyzer ids1 rules enable system signatures/web-application-attack.ids"

echo 'Настройка ids2'
/bin/argsh -c "services analyzer ids2 rules enable system check_listen_interface.ids; services analyzer ids2 rules enable system detect-ftp-bruteforcing.ids; services analyzer ids2 rules enable system detect-http-bruteforcing.ids; services analyzer ids2 rules enable system detect-http-xss.ids; services analyzer ids2 rules enable system detect-sqlinjection.ids; services analyzer ids2 rules enable system detect-ssh-bruteforcing.ids; services analyzer ids2 rules enable system scan.ids; services analyzer ids2 rules enable system signatures/attempted-admin.ids; services analyzer ids2 rules enable system signatures/attempted-dos.ids; services analyzer ids2 rules enable system signatures/attempted-recon.ids; services analyzer ids2 rules enable system signatures/attempted-user.ids; services analyzer ids2 rules enable system signatures/bad-unknown.ids; services analyzer ids2 rules enable system signatures/default-login-attempt.ids; services analyzer ids2 rules enable system signatures/denial-of-service.ids; services analyzer ids2 rules enable system signatures/misc-attack.ids; services analyzer ids2 rules enable system signatures/policy-violation.ids; services analyzer ids2 rules enable system signatures/protocol-command-decode.ids; services analyzer ids2 rules enable system signatures/successful-recon-largescale.ids; services analyzer ids2 rules enable system signatures/suspicious-filename-detect.ids; services analyzer ids2 rules enable system signatures/trojan-activity.ids; services analyzer ids2 rules enable system signatures/unknown.ids; services analyzer ids2 rules enable system signatures/web-application-activity.ids; services analyzer ids2 rules enable system signatures/web-application-attack.ids"

echo 'Запуск сигнатурных анализаторов'
/bin/argsh -c "services analyzer ids0 start; services analyzer ids1 start; services analyzer ids2 start"

echo 'Сохранение конфигурации'
/bin/argsh -c "config write"
